### ISSUE TITLE
Exmaples 

### ISSUE THREAD

**Issue by Charley-Mann** [NPDeehan/Sorting-Hat-DMN-Example#1]
Hey Niall

I'm working with Brittany to get this ready for the Camunda blog and I spotted a few teeny tiny typos on the repo I was hoping you could fix? 

-In the title, we've got "exmaple" instead of "example" 
-In the description, could you please capitalize the Sorting Hat and Harry Potter?

I also fired over a PR asking if we could change Horkrux to Horcrux -- totally happy if it's by title only and everything in the backend stays as is -- LMK what you think.

Thank you!

**Comment by NPDeehan** [comment]
Thanks charlie i'll do that now!

**Comment by NPDeehan** [comment]
I've updated the issues :)
